name: Build JAR

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Corretto 16
        run: |
          wget https://corretto.aws/downloads/latest/amazon-corretto-16-aarch64-linux-jdk.deb
          dpkg -i amazon-corretto-16-aarch64-linux-jdk.deb
          java -version
      - name: Set up Maven
        run: sudo apt install maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml