name: Build JAR

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: joschi/setup-jdk@v2
        with:
          java-version: '16' # The OpenJDK version to make available on the path
          architecture: 'x64' # defaults to 'x64'
      - name: Build with Maven
        run: mvn package && mv /home/runner/query_bot-1.0-SNAPSHOT-shaded.jar /home/runner/ts3_query_bot.jar
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: Nightly Build
          path: /home/runner/ts3_query_bot.jar
          retention-days: 5
