name: Build JAR

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: joschi/setup-jdk@v2
        with:
          java-version: '16' # The OpenJDK version to make available on the path
          architecture: 'x64' # defaults to 'x64'
      - name: Build with Maven
        run: |
          mvn package
          mv /home/runner/work/TS3-Query-Bot/TS3-Query-Bot/target/query_bot-1.0-SNAPSHOT.jar /home/runner/ts3_query_bot.jar
          mv /home/runner/work/TS3-Query-Bot/TS3-Query-Bot/config/*.json /home/runner
          mv /home/runner/example_config.json /home/runner/config.json
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: Nightly Build
          path: |
            /home/runner/ts3_query_bot.jar
            /home/runner/*.json
          retention-days: 30
